plugins:
  discourse_toc_enabled:
    client: true
    default: true
    description: "Enable automatic Table of Contents generation for posts with headers"
  discourse_toc_min_header_level:
    client: true
    default: 1
    min: 1
    max: 6
    description: "Minimum header level to include in TOC (1=H1, 2=H2, etc). Headers at this level and above will be included."